In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import re

In [2]:
test_seqs = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/consensus_AD_predictor/output/screen_test_seqs_with_activities.csv')

In [3]:
test_seqs['screen'].value_counts()

screen
ravarani    27093
hummel      15864
arf          9056
sanborn      8288
delrosso      804
arnold        240
Name: count, dtype: int64

In [5]:
amino_acids = ['A','C','D','E','F','G','H','I','K','L','M','N','P','Q','R','S','T','V','W','Y']

In [9]:
amino_acids = ['A','C','D','E','F','G','H','I','K','L','M','N','P','Q','R','S','T','V','W','Y']
for seq in test_seqs['protein sequence']:
    if len(set(seq).difference(amino_acids)) > 0:
        print(seq)

In [16]:
"arf_KRH 74145_1".replace(' ', "_")

'arf_KRH_74145_1'

In [26]:
test_seqs['id'] = [re.sub(r"\s+", "-", id) for id in test_seqs['id']]

In [27]:
for id in test_seqs['id']:
    split_ids = id.split()
    if len(split_ids) > 1:
        # print(id)
        print(re.sub(r"\s+", "-", id))

In [ ]:
# Have made predictions on all of hummel, some of sanborn, all of delrosso, and some of arnold
# Ravarani seqs are too short
# Some sanborn are too short

In [11]:
sanborn = test_seqs[test_seqs['screen'] == 'sanborn']
sanborn

,Unnamed: 0,id,protein sequence,activity,screen
9056,0,sanborn_D_ADbest-AA-muts_P07248_415_DE,SENQPEFVEFQELLENETLGNELLETTAVLKEFELLHEESVSATAT...,4.55,sanborn
9057,1,sanborn_D_ADbest-AA-muts_P07248_415_ED,SDNQPDFVDFQDLLDNDTLGNDLLDTTAVLKDFDLLHDDSVSATAT...,6.51,sanborn
9058,2,sanborn_D_ADbest-AA-muts_P07248_648_DE,LPHFPIIHPSLLELELESLQRYTNEEGYEEAENAQLFERLSQGTEK...,3.49,sanborn
9059,3,sanborn_D_ADbest-AA-muts_P07248_648_ED,LPHFPIIHPSLLDLDLDSLQRYTNDDGYDDADNAQLFDRLSQGTDK...,4.70,sanborn
9060,4,sanborn_D_ADbest-AA-muts_P07269_0_DE,MMEEFSYEHEFNTHFATELEYLQHEQQQQQQQQHEQQHNQQQQPQP...,3.55,sanborn
...,...,...,...,...,...
17339,2066,sanborn_D_nuc-nonhits_Q03656_575,LLGAPWGCGADIWSTACLIFELITGDFLFEPDEGHSYTKDDDHIAQ...,-0.20,sanborn
17340,2067,sanborn_D_nuc-nonhits_P17883_860,QVLRLFIWIESKVDTLPVESLVSIFENSQFSGSEEIDSVDNIKIDT...,-0.22,sanborn
17341,2068,sanborn_D_nuc-nonhits_P53036_375,QRDPVYLGHLLYELTMHMEDFYALLIKLENDDDDDHDTASKALPSV...,-0.22,sanborn
17342,2069,sanborn_D_nuc-nonhits_P22211_487,EYCIGTTLNHPNIIETIEIVYENDRILQVMEYCEYDLFAIVMSNKM...,-0.29,sanborn
17343,2070,sanborn_D_nuc-nonhits_P38217_700,CLQDPVHEVRQSCFALLGDIVYFFNSELVIGNLEDFLKLIGTEIMH...,-0.61,sanborn

In [14]:
sanborn[sanborn['protein sequence'].str.len() >=53]

,Unnamed: 0,id,protein sequence,activity,screen
9056,0,sanborn_D_ADbest-AA-muts_P07248_415_DE,SENQPEFVEFQELLENETLGNELLETTAVLKEFELLHEESVSATAT...,4.55,sanborn
9057,1,sanborn_D_ADbest-AA-muts_P07248_415_ED,SDNQPDFVDFQDLLDNDTLGNDLLDTTAVLKDFDLLHDDSVSATAT...,6.51,sanborn
9058,2,sanborn_D_ADbest-AA-muts_P07248_648_DE,LPHFPIIHPSLLELELESLQRYTNEEGYEEAENAQLFERLSQGTEK...,3.49,sanborn
9059,3,sanborn_D_ADbest-AA-muts_P07248_648_ED,LPHFPIIHPSLLDLDLDSLQRYTNDDGYDDADNAQLFDRLSQGTDK...,4.70,sanborn
9060,4,sanborn_D_ADbest-AA-muts_P07269_0_DE,MMEEFSYEHEFNTHFATELEYLQHEQQQQQQQQHEQQHNQQQQPQP...,3.55,sanborn
...,...,...,...,...,...
17339,2066,sanborn_D_nuc-nonhits_Q03656_575,LLGAPWGCGADIWSTACLIFELITGDFLFEPDEGHSYTKDDDHIAQ...,-0.20,sanborn
17340,2067,sanborn_D_nuc-nonhits_P17883_860,QVLRLFIWIESKVDTLPVESLVSIFENSQFSGSEEIDSVDNIKIDT...,-0.22,sanborn
17341,2068,sanborn_D_nuc-nonhits_P53036_375,QRDPVYLGHLLYELTMHMEDFYALLIKLENDDDDDHDTASKALPSV...,-0.22,sanborn
17342,2069,sanborn_D_nuc-nonhits_P22211_487,EYCIGTTLNHPNIIETIEIVYENDRILQVMEYCEYDLFAIVMSNKM...,-0.29,sanborn
17343,2070,sanborn_D_nuc-nonhits_P38217_700,CLQDPVHEVRQSCFALLGDIVYFFNSELVIGNLEDFLKLIGTEIMH...,-0.61,sanborn

In [18]:
"TEST".contains("T")

AttributeError: 'str' object has no attribute 'contains'

In [22]:
sum(['7' in s for s in test_seqs['protein sequence']])

0

In [28]:
test_seqs[['id','protein sequence']].to_csv('../test_seq_predictions/all_test_seqs.tsv', sep=' ', index=None, header=None)

# Marissa synthetics

In [3]:
synthetics = pd.read_csv('../test_seq_predictions/Synthetics_Activities.csv')
synthetics['id'] = synthetics.index
synthetics

,AAseq,Activity,StdDev,Activity_GFP,StdDev_GFP,Activity_mCherry,StdDev_mCherry,id
0,AAAAAIACELRTDNYFEYPDLSILDALDNDSDETMSLIDE,0.473609,NaN,0.575642,NaN,468.881757,NaN,0
1,AAAAASDHSDVNDIIELGGLSNRLYDFYSDLEDIENDIAV,0.903132,NaN,0.733105,NaN,312.143504,NaN,1
2,AAADGASFSDDTDEDLYKYDPWDLPGLSVIKTDDPEWFFF,3.868678,0.222749,3.061543,0.369973,240.421461,34.900357,2
3,AAADGASFSDDTDEDLYKYDPWELPSKASFGEQEWYFFSP,2.469731,0.256302,1.888136,0.463168,252.884922,50.010381,3
4,AAADGPDCDTREFCELRDSLLWNESCFLLDDDKRFDVSEN,1.236664,NaN,2.249856,NaN,440.446675,NaN,4
...,...,...,...,...,...,...,...,...
16765,YYSDDIMLDLGVDLSNFQFDFRYFGLDSPLSPPWNEDDDS,5.990318,0.129122,6.290907,0.508324,161.573960,55.704165,16765
16766,YYSEQSCYLDLDLDLDITFLDFSQFLEQLLQSKNDPLVSE,5.587220,0.645912,6.227913,0.048433,159.374865,NaN,16766
16767,YYSEQSCYLNFPPLDCVDLVATLSEKFKSFSQLLLDFPIS,0.981382,NaN,-0.744936,NaN,109.030773,NaN,16767
16768,YYSEQSCYLNFPPLDMFPALPSDLSGWVESMLSELNNPAS,3.257207,0.058277,2.900316,0.100772,250.454172,47.344796,16768
16769,YYSSLGVEPWDLDGLFEFSRLLVDLNMDGFKIDWDYEVAE,3.204264,0.515034,2.286465,0.436093,186.199648,19.123939,16769

In [4]:
synthetics[['id','AAseq']].to_csv('../test_seq_predictions/synthetics_test_seqs.tsv', sep=' ', index=None, header=None)

In [6]:
with open('../test_seq_predictions/synthetics_test_seqs.fasta', 'w+') as f: 
    for i in synthetics.index:
        f.write(">" + str(synthetics.loc[i, 'id']) + "\n")
        f.write(synthetics.loc[i, 'AAseq'] + "\n")