In [1]:
import pandas as pd
from tqdm import tqdm
import os
import ast

In [2]:
with open('../cl_seqs_filtered.txt', 'r') as f:
    seqs_to_keep = f.readlines()

seqs_to_keep = [s.strip() for s in seqs_to_keep]

In [3]:
df_list = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_all_six.csv", index_col=0)
        df_list.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except: 
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:52<02:06,  1.27s/it]

duplicates

 31%|███       | 43/138 [00:55<00:57,  1.64it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:57<01:32,  1.02it/s]

.gitignore

 56%|█████▌    | 77/138 [01:34<01:17,  1.27s/it]

.DS_Store

 80%|████████  | 111/138 [02:26<00:40,  1.48s/it]

.git

 91%|█████████ | 125/138 [02:44<00:15,  1.17s/it]

README.md

100%|██████████| 138/138 [03:00<00:00,  1.30s/it]

In [4]:
filtered_seqs = pd.concat(df_list, ignore_index = True)
filtered_seqs

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals,composition_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15312937,0.14884889,0.14245647,0.14149511,0...","[0.00010605756,6.128723e-05,0.00010040323,6.17...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.037470482,-0.043542463,-0.05288577,-0.0629...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.093698501586914,-1.0776761770248413,-1.058...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]","[(70, 118), (347, 388)]",NaN,NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16891767,0.17582706,0.17177798,0.16646911,0...","[0.00048471623,0.0002901567,0.00030327312,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[-0.078374624,-0.078347124,-0.077769004,-0.077...","[27,28,29,30,31,32,33,34]","[-0.735693097114563,-0.7156334519386292,-0.648...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15832736,0.15381505,0.15814708,0.167217,0.1...","[0.000233731,0.0006135058,0.00052977534,0.0008...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.0008075237,-0.009743293,-0.020115647,-0.028...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7945389747619629,-0.9303826093673706,-0.88...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(94, 150), (308, 376), (455, 517), (696, 746)]","[(332, 358)]",NaN,"[(305, 359), (453, 507)]","[(323, 373), (460, 517)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16003162,0.16763635,0.17131436,0.17730847,0...","[0.00023327394,0.00022822362,0.00020547971,9.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.07605376,-0.0749253,-0.07407423,-0.0726430...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7241523861885071,-0.7126811146736145,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(60, 113)]",NaN,NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17539005,0.1755809,0.17338772,0.16945839,0....","[0.00012658811,0.00033318822,0.00027224806,0.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.113887355,0.12466081,0.12549822,0.12015024,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.903002917766571,-0.834099292755127,-0.8482...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(100, 157)]","[(125, 135)]",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95629,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.6666666666666666,0.8333333333333334,0.83333...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(0, 65)]","[(1, 53)]"
95630,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.16666666666666666,0.16666666666666666,0.166...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(0, 164)]","[(19, 143)]","[(33, 80)]"
95631,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.5,0.5,0.5,0.5,0.6666666666666666,0.66666666...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]","[(9, 84)]"
95632,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.6666666666666666,1.0,1.0,1.0,1.0,1.0,1.0,1....","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 138)]","[(0, 106)]","[(1, 44)]"
95633,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.6666666666666666,0.8333333333333334,0.83333...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 92)]","[(0, 65)]","[(1, 54)]"

In [5]:
# Currently just missing sequences from Flo
len(seqs_to_keep)

95634

In [6]:
len(set(seqs_to_keep).difference(filtered_seqs['name']))

0

In [7]:
len(set(filtered_seqs['name']).difference(seqs_to_keep))

0

In [8]:
filtered_seqs['length'] = filtered_seqs['sequence'].str.len()

In [9]:
filtered_seqs[filtered_seqs['length'] <= 53]

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals,composition_intervals,length
4405,g016736.m1_yHMPu5000034630_Magnusiomyces_magnu...,MPFSSPPTGTSPFSALHTSIESPGYIGSRQNSINMSASAVENNRYA...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[61192.637,44867.95,40146.67,32508.598,23319.3...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17978503,0.18038991,0.17954087,0.17649332,0...","[0.001194003,0.003034387,0.002344234,0.0026009...",[27.0],[1.0122999],[27],[-0.34304875135421753],[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN,53
13096,g005469.m1_yHMPu5000037893_candida_ovalis_1709...,DSGFDPEKTKIARNSAFFTPAELDFLNRCDSRKEKLMRSISLINEK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[44046.95,47183.926,48888.75,50178.254,48757.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.26164922,0.25543454,0.23452474,0.22270612,0...","[0.00022028793,0.00023026927,0.0006861787,0.00...",[27.0],[0.2713585],[27],[-0.3103697896003723],[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN,53
23002,g004903.m1_yHMPu5000034585_candida_floris_1909...,MANHYHNWQGQQGSTEDIYQAQSEEWAPQQAAQPHHQQQQQQQQQQ...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[30655.812,29540.664,29300.79,28066.379,28638....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.19286619,0.19165453,0.19693467,0.19435678,0...","[0.0004803675,0.00058629696,0.00066192675,0.00...",[27.0],[1.2509137],[27],[-0.8754321932792664],[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN,53
36639,g006075.m1_yHMPu5000037207_Wickerhamomyces_kur...,MNERRKITPINPLDITESLGYTTFRRDSRKPWTKEDDEFLKELINA...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[35022.543,29858.797,26049.488,31759.078,42497...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.26028976,0.27949485,0.2621777,0.29613706,0....","[0.0008486381,0.00081409083,0.00089034217,0.00...",[27.0],[1.2286111],[27],[0.2796017527580261],[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN,53
47319,g000682.m1_yHMPu5000034753_dipodascopsis_uninu...,MTGGSPHSNTAATSPSSANNRENRGSSFEEGSSYGNATRSKFDLEP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[21399.434,22181.8,28074.715,20952.363,23082.3...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.1596271,0.16155809,0.16709058,0.17208266,0....","[0.00010163313,9.744259e-05,8.489941e-05,9.895...",[27.0],[0.555856],[27],[-0.8776400685310364],[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN,53
70555,g006875.m1_yHMPu5000034738_geotrichum_candidum...,MEPSDSQSIVPLTNILNELVQLKYFLLTGPAQLRTENGIHRHTLPN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[28060.672,27141.586,26920.098,27486.469,28714...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.19783494,0.1878926,0.1864837,0.18842806,0.1...","[0.004205272,0.011561773,0.017290646,0.0153780...",[27.0],[-0.011953354],[27],[-0.5188935995101929],[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN,53

In [10]:
# Write to output file
filtered_seqs.to_csv('../predictions/combined_preds/y1000_filtered_all_six_combined.csv')

In [11]:
# Read in y-1000 seqs here
all_combined_all_six_filtered_y1000 = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/y1000_filtered_all_six_combined.csv', 
                                  index_col=0,
                                  converters={'combined_preds' : ast.literal_eval})

In [12]:
df = all_combined_all_six_filtered_y1000['combined_preds'].apply(pd.Series)

In [13]:
df.max().max()

1.0

# Excluding the composition model

In [17]:
df_list_no_comp = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_no_composition.csv", index_col=0)
        df_list_no_comp.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except: 
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:48<02:04,  1.25s/it]

duplicates

 31%|███       | 43/138 [00:50<00:56,  1.68it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:52<01:27,  1.07it/s]

.gitignore

 56%|█████▌    | 77/138 [01:30<01:12,  1.19s/it]

.DS_Store

 80%|████████  | 111/138 [02:21<00:36,  1.37s/it]

.git

 91%|█████████ | 125/138 [02:39<00:13,  1.05s/it]

README.md

100%|██████████| 138/138 [02:55<00:00,  1.27s/it]

In [18]:
filtered_seqs_no_comp = pd.concat(df_list_no_comp, ignore_index = True)
filtered_seqs_no_comp

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15312937,0.14884889,0.14245647,0.14149511,0...","[0.00010605756,6.128723e-05,0.00010040323,6.17...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.037470482,-0.043542463,-0.05288577,-0.0629...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.093698501586914,-1.0776761770248413,-1.058...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]","[(70, 118), (347, 388)]",NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16891767,0.17582706,0.17177798,0.16646911,0...","[0.00048471623,0.0002901567,0.00030327312,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[-0.078374624,-0.078347124,-0.077769004,-0.077...","[27,28,29,30,31,32,33,34]","[-0.735693097114563,-0.7156334519386292,-0.648...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15832736,0.15381505,0.15814708,0.167217,0.1...","[0.000233731,0.0006135058,0.00052977534,0.0008...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.0008075237,-0.009743293,-0.020115647,-0.028...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7945389747619629,-0.9303826093673706,-0.88...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(94, 150), (308, 376), (455, 517), (696, 746)]","[(332, 358)]",NaN,"[(305, 359), (453, 507)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16003162,0.16763635,0.17131436,0.17730847,0...","[0.00023327394,0.00022822362,0.00020547971,9.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.07605376,-0.0749253,-0.07407423,-0.0726430...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7241523861885071,-0.7126811146736145,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(60, 113)]",NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17539005,0.1755809,0.17338772,0.16945839,0....","[0.00012658811,0.00033318822,0.00027224806,0.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.113887355,0.12466081,0.12549822,0.12015024,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.903002917766571,-0.834099292755127,-0.8482...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(100, 157)]","[(125, 135)]",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95629,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(0, 65)]"
95630,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.2,0.2,0.2,0.2,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(0, 164)]","[(19, 143)]"
95631,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.6,0.6,0.6,0.6,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]"
95632,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 138)]","[(0, 106)]"
95633,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.8,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1.0,1...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 92)]","[(0, 65)]"

In [19]:
len(set(seqs_to_keep).difference(filtered_seqs_no_comp['name']))

0

In [20]:
len(set(filtered_seqs_no_comp['name']).difference(seqs_to_keep))

0

In [21]:
filtered_seqs_no_comp.to_csv('../predictions/combined_preds/y1000_filtered_no_sanjana_combined.csv')

In [22]:
# Read in y-1000 seqs here
all_combined_no_sanjana_filtered_y1000 = pd.read_csv('/global/scratch/projects/fc_mvslab/OpenProjects/Claire/consensus_predictor/predictions/combined_preds/y1000_filtered_no_sanjana_combined.csv', 
                                  index_col=0,
                                  converters={'combined_preds' : ast.literal_eval})

In [23]:
df = all_combined_no_sanjana_filtered_y1000['combined_preds'].apply(pd.Series)

In [24]:
df.max().max()

1.0

# Excluding ADhunterLite

In [25]:
df_list_no_adhunterlite = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_no_ADhunterLite.csv", index_col=0)
        df_list_no_adhunterlite.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except:
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:50<02:00,  1.21s/it]

duplicates

 31%|███       | 43/138 [00:53<00:54,  1.73it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:55<01:30,  1.04it/s]

.gitignore

 56%|█████▌    | 77/138 [01:31<01:12,  1.19s/it]

.DS_Store

 80%|████████  | 111/138 [02:21<00:38,  1.41s/it]

.git

 91%|█████████ | 125/138 [02:38<00:13,  1.01s/it]

README.md

100%|██████████| 138/138 [02:53<00:00,  1.26s/it]

In [26]:
filtered_seqs_no_adhunterlite = pd.concat(df_list_no_adhunterlite, ignore_index = True)
filtered_seqs_no_adhunterlite

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals,composition_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15312937,0.14884889,0.14245647,0.14149511,0...","[0.00010605756,6.128723e-05,0.00010040323,6.17...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.037470482,-0.043542463,-0.05288577,-0.0629...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.093698501586914,-1.0776761770248413,-1.058...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]","[(70, 118), (347, 388)]",NaN,NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16891767,0.17582706,0.17177798,0.16646911,0...","[0.00048471623,0.0002901567,0.00030327312,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[-0.078374624,-0.078347124,-0.077769004,-0.077...","[27,28,29,30,31,32,33,34]","[-0.735693097114563,-0.7156334519386292,-0.648...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15832736,0.15381505,0.15814708,0.167217,0.1...","[0.000233731,0.0006135058,0.00052977534,0.0008...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.0008075237,-0.009743293,-0.020115647,-0.028...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7945389747619629,-0.9303826093673706,-0.88...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(94, 150), (308, 376), (455, 517), (696, 746)]","[(332, 358)]",NaN,"[(305, 359), (453, 507)]","[(323, 373), (460, 517)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16003162,0.16763635,0.17131436,0.17730847,0...","[0.00023327394,0.00022822362,0.00020547971,9.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.07605376,-0.0749253,-0.07407423,-0.0726430...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7241523861885071,-0.7126811146736145,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(60, 113)]",NaN,NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17539005,0.1755809,0.17338772,0.16945839,0....","[0.00012658811,0.00033318822,0.00027224806,0.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.113887355,0.12466081,0.12549822,0.12015024,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.903002917766571,-0.834099292755127,-0.8482...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(100, 157)]","[(125, 135)]",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95629,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.6666666666666666,0.8333333333333334,0.83333...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(0, 65)]","[(1, 53)]"
95630,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.16666666666666666,0.16666666666666666,0.166...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(0, 164)]","[(19, 143)]","[(33, 80)]"
95631,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.5,0.5,0.5,0.5,0.6666666666666666,0.66666666...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]","[(9, 84)]"
95632,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.6666666666666666,1.0,1.0,1.0,1.0,1.0,1.0,1....","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 138)]","[(0, 106)]","[(1, 44)]"
95633,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.6666666666666666,0.8333333333333334,0.83333...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 92)]","[(0, 65)]","[(1, 54)]"

In [27]:
len(set(seqs_to_keep).difference(filtered_seqs_no_adhunterlite['name']))

0

In [28]:
len(set(filtered_seqs_no_adhunterlite['name']).difference(seqs_to_keep))

0

In [29]:
set(seqs_to_keep).difference(filtered_seqs_no_adhunterlite['name'])

set()

In [30]:
filtered_seqs_no_adhunterlite.to_csv('../predictions/combined_preds/y1000_filtered_no_adhunterlite_combined.csv')

# Excluding ADhunterEnsemble

In [32]:
df_list_no_adhunterensemble = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_no_ADhunterEnsemble.csv", index_col=0)
        df_list_no_adhunterensemble.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except:
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:40<01:35,  1.04it/s]

duplicates

 30%|██▉       | 41/138 [00:41<01:10,  1.37it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:43<01:01,  1.52it/s]

.gitignore

 56%|█████▌    | 77/138 [01:11<00:56,  1.09it/s]

.DS_Store

 59%|█████▉    | 82/138 [01:12<00:19,  2.88it/s]

Gzf3

 80%|████████  | 111/138 [01:47<00:29,  1.08s/it]

.git

 91%|█████████ | 125/138 [02:02<00:11,  1.12it/s]

README.md

100%|██████████| 138/138 [02:14<00:00,  1.03it/s]

In [33]:
filtered_seqs_no_adhunterensemble = pd.concat(df_list_no_adhunterensemble, ignore_index = True)
filtered_seqs_no_adhunterensemble

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,composition_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15312937,0.14884889,0.14245647,0.14149511,0...","[0.00010605756,6.128723e-05,0.00010040323,6.17...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.037470482,-0.043542463,-0.05288577,-0.0629...","[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]","[(70, 118), (347, 388)]",NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16891767,0.17582706,0.17177798,0.16646911,0...","[0.00048471623,0.0002901567,0.00030327312,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[-0.078374624,-0.078347124,-0.077769004,-0.077...","[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15832736,0.15381505,0.15814708,0.167217,0.1...","[0.000233731,0.0006135058,0.00052977534,0.0008...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.0008075237,-0.009743293,-0.020115647,-0.028...","[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(94, 150), (308, 376), (455, 517), (696, 746)]","[(332, 358)]",NaN,"[(323, 373), (460, 517)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16003162,0.16763635,0.17131436,0.17730847,0...","[0.00023327394,0.00022822362,0.00020547971,9.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.07605376,-0.0749253,-0.07407423,-0.0726430...","[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(60, 113)]",NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17539005,0.1755809,0.17338772,0.16945839,0....","[0.00012658811,0.00033318822,0.00027224806,0.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.113887355,0.12466081,0.12549822,0.12015024,...","[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(100, 157)]","[(125, 135)]",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91704,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[0.6,0.8,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(1, 53)]"
91705,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[0.2,0.2,0.2,0.2,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(0, 164)]","[(33, 80)]"
91706,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[0.4,0.4,0.4,0.4,0.6,0.6,0.6,0.6,0.6,0.8,0.8,0...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(9, 84)]"
91707,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[0.6,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 138)]","[(1, 44)]"
91708,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[0.6,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1.0,1...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 92)]","[(1, 54)]"

In [34]:
len(set(seqs_to_keep).difference(filtered_seqs_no_adhunterensemble['name']))

3925

In [35]:
len(set(filtered_seqs_no_adhunterensemble['name']).difference(seqs_to_keep))

0

In [36]:
filtered_seqs_no_adhunterensemble.to_csv('../predictions/combined_preds/y1000_filtered_no_adhunterensemble_combined.csv')

# Excluding ADpred

In [37]:
df_list_no_adpred = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_no_adpred.csv", index_col=0)
        df_list_no_adpred.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except: 
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:47<01:55,  1.15s/it]

duplicates

 30%|██▉       | 41/138 [00:49<01:24,  1.15it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:51<01:26,  1.09it/s]

.gitignore

 56%|█████▌    | 77/138 [01:26<01:09,  1.14s/it]

.DS_Store

 58%|█████▊    | 80/138 [01:26<00:34,  1.66it/s]

Gzf3

 80%|████████  | 111/138 [02:09<00:36,  1.35s/it]

.git

 91%|█████████ | 125/138 [02:26<00:13,  1.01s/it]

README.md

100%|██████████| 138/138 [02:41<00:00,  1.17s/it]

In [38]:
filtered_seqs_no_adpred = pd.concat(df_list_no_adpred, ignore_index = True)
filtered_seqs_no_adpred

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,paddle_intervals,adhunter_ensemble_intervals,composition_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15312937,0.14884889,0.14245647,0.14149511,0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.037470482,-0.043542463,-0.05288577,-0.0629...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.093698501586914,-1.0776761770248413,-1.058...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]","[(70, 118), (347, 388)]",NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16891767,0.17582706,0.17177798,0.16646911,0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[-0.078374624,-0.078347124,-0.077769004,-0.077...","[27,28,29,30,31,32,33,34]","[-0.735693097114563,-0.7156334519386292,-0.648...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15832736,0.15381505,0.15814708,0.167217,0.1...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.0008075237,-0.009743293,-0.020115647,-0.028...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7945389747619629,-0.9303826093673706,-0.88...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(94, 150), (308, 376), (455, 517), (696, 746)]",NaN,"[(305, 359), (453, 507)]","[(323, 373), (460, 517)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16003162,0.16763635,0.17131436,0.17730847,0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.07605376,-0.0749253,-0.07407423,-0.0726430...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7241523861885071,-0.7126811146736145,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(60, 113)]",NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17539005,0.1755809,0.17338772,0.16945839,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.113887355,0.12466081,0.12549822,0.12015024,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.903002917766571,-0.834099292755127,-0.8482...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(100, 157)]",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91704,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 61)]","[(0, 72), (98, 167)]","[(0, 83), (85, 177)]","[(0, 65)]","[(1, 53)]"
91705,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.2,0.2,0.2,0.2,0.4,0.6,0.6,0.6,0.6,0.6,0.6,0...","[(5, 86), (87, 140)]","[(4, 147)]","[(0, 164)]","[(19, 143)]","[(33, 80)]"
91706,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.6,0.6,0.6,0.6,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]","[(9, 84)]"
91707,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(0, 138)]","[(0, 106)]","[(1, 44)]"
91708,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.8,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(0, 92)]","[(0, 65)]","[(1, 54)]"

In [39]:
len(set(seqs_to_keep).difference(filtered_seqs_no_adpred['name']))

3925

In [40]:
len(set(filtered_seqs_no_adpred['name']).difference(seqs_to_keep))

0

In [41]:
filtered_seqs_no_adpred.to_csv('../predictions/combined_preds/y1000_filtered_no_adpred_combined.csv')

# Excluding TADA

In [42]:
df_list_no_tada = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_no_tada.csv", index_col=0)
        df_list_no_tada.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except: 
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:51<02:28,  1.48s/it]

duplicates

 31%|███       | 43/138 [00:54<01:06,  1.43it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:56<01:38,  1.05s/it]

.gitignore

 56%|█████▌    | 77/138 [01:34<01:09,  1.13s/it]

.DS_Store

 58%|█████▊    | 80/138 [01:35<00:35,  1.63it/s]

Gzf3

 80%|████████  | 111/138 [02:22<00:35,  1.31s/it]

.git

 91%|█████████ | 125/138 [02:39<00:13,  1.00s/it]

README.md

100%|██████████| 138/138 [02:54<00:00,  1.27s/it]

In [43]:
filtered_seqs_no_tada = pd.concat(df_list_no_tada, ignore_index = True)
filtered_seqs_no_tada

,name,sequence,adhunter_centers,adhunter_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals,composition_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[0.00010605756,6.128723e-05,0.00010040323,6.17...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.037470482,-0.043542463,-0.05288577,-0.0629...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.093698501586914,-1.0776761770248413,-1.058...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]",NaN,NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[0.00048471623,0.0002901567,0.00030327312,0.00...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0]","[-0.078374624,-0.078347124,-0.077769004,-0.077...","[27,28,29,30,31,32,33,34]","[-0.735693097114563,-0.7156334519386292,-0.648...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[0.000233731,0.0006135058,0.00052977534,0.0008...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.0008075237,-0.009743293,-0.020115647,-0.028...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7945389747619629,-0.9303826093673706,-0.88...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(332, 358)]",NaN,"[(305, 359), (453, 507)]","[(323, 373), (460, 517)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[0.00023327394,0.00022822362,0.00020547971,9.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.07605376,-0.0749253,-0.07407423,-0.0726430...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7241523861885071,-0.7126811146736145,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[0.00012658811,0.00033318822,0.00027224806,0.0...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.113887355,0.12466081,0.12549822,0.12015024,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.903002917766571,-0.834099292755127,-0.8482...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(125, 135)]",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91704,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.6,0.8,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1...","[(0, 61)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(0, 65)]","[(1, 53)]"
91705,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.2,0.2,0.2,0.2,0.2,0.4,0.4,0.4,0.4,0.4,0.4,0...","[(5, 86), (87, 140)]","[(38, 56), (112, 122)]","[(0, 164)]","[(19, 143)]","[(33, 80)]"
91706,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.4,0.4,0.4,0.4,0.6,0.6,0.6,0.6,0.6,0.8,0.8,0...","[(4, 87), (111, 190)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]","[(9, 84)]"
91707,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.6,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 55), (64, 108)]","[(1, 27)]","[(0, 138)]","[(0, 106)]","[(1, 44)]"
91708,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.6,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1.0,1...","[(0, 53), (90, 130)]","[(7, 38)]","[(0, 92)]","[(0, 65)]","[(1, 54)]"

In [44]:
len(set(seqs_to_keep).difference(filtered_seqs_no_tada['name']))

3925

In [45]:
len(set(filtered_seqs_no_tada['name']).difference(seqs_to_keep))

0

In [46]:
filtered_seqs_no_tada.to_csv('../predictions/combined_preds/y1000_filtered_no_tada_combined.csv')

# Excluding PADDLE

In [47]:
df_list_no_paddle = []
for item_name in tqdm(os.listdir("/global/scratch/users/claireleblanc/transcription_factors/")):
    try: 
        preds = pd.read_csv(f"/global/scratch/users/claireleblanc/transcription_factors/{item_name}/{item_name}_orthologs_consensus_no_paddle.csv", index_col=0)
        df_list_no_paddle.append(preds[[n in seqs_to_keep for n in preds['name']]])
    except: 
        print(item_name)

  0%|          | 0/138 [00:00<?, ?it/s]

analysis_scripts

 28%|██▊       | 38/138 [00:47<01:57,  1.18s/it]

duplicates

 31%|███       | 43/138 [00:49<00:53,  1.79it/s]

all_TFs.csv

 32%|███▏      | 44/138 [00:51<01:22,  1.13it/s]

.gitignore

 56%|█████▌    | 77/138 [01:26<01:08,  1.13s/it]

.DS_Store

 58%|█████▊    | 80/138 [01:27<00:35,  1.62it/s]

Gzf3

 80%|████████  | 111/138 [02:11<00:35,  1.33s/it]

.git

 91%|█████████ | 125/138 [02:27<00:12,  1.04it/s]

README.md

100%|██████████| 138/138 [02:42<00:00,  1.18s/it]

In [48]:
filtered_seqs_no_paddle = pd.concat(df_list_no_paddle, ignore_index = True)
filtered_seqs_no_paddle

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,adhunter_ensemble_intervals,composition_intervals
0,g001536.m1_brettanomyces_anomalus.final,MSDKPHNQYACTRCRRLKKKCSKEFPRCANCRKQNKVCEYVERKNK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[39868.07,41361.715,31523.598,28429.61,25309.8...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15312937,0.14884889,0.14245647,0.14149511,0...","[0.00010605756,6.128723e-05,0.00010040323,6.17...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-1.093698501586914,-1.0776761770248413,-1.058...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(646, 688)]","[(70, 118), (347, 388)]",NaN,NaN,NaN
1,C1_01200W_A_candida_albicans.cgd,MRPIDSIVSKFRVQKHTSNLADNPAVLKHPEDMPKLTSCLRCRKLK...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[41180.59,34131.055,35682.168,32408.352,25205....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16891767,0.17582706,0.17177798,0.16646911,0...","[0.00048471623,0.0002901567,0.00030327312,0.00...","[27,28,29,30,31,32,33,34]","[-0.735693097114563,-0.7156334519386292,-0.648...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,NaN,NaN,NaN,NaN
2,g001338.m1_candida_parapsilosis.final,MLSPESSVTKFRVKKFPVTDGNGNNFSHHQIEQIANEPVAKVTSCL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[38912.785,32041.488,42465.785,43528.59,39058....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15832736,0.15381505,0.15814708,0.167217,0.1...","[0.000233731,0.0006135058,0.00052977534,0.0008...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7945389747619629,-0.9303826093673706,-0.88...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(308, 384), (700, 746)]","[(94, 150), (308, 376), (455, 517), (696, 746)]","[(332, 358)]","[(305, 359), (453, 507)]","[(323, 373), (460, 517)]"
3,g002226.m1_candida_sojae.final,MSTEPIVTKFRVKKPTTKAPSSNDLIKDISKLTSCLRCRKLKKKCN...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[20203.137,32381.984,40072.316,29473.3,25579.6...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.16003162,0.16763635,0.17131436,0.17730847,0...","[0.00023327394,0.00022822362,0.00020547971,9.0...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7241523861885071,-0.7126811146736145,-0.69...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...",NaN,"[(60, 113)]",NaN,NaN,NaN
4,g002657.m1_eremothecium_sinecaudum.final,MQPKMSEARTVTSVQFNDGLKYASYSCSRCRRLKKKCSKAIPTCYS...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[32827.797,38615.387,31616.844,39608.03,44944....","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.17539005,0.1755809,0.17338772,0.16945839,0....","[0.00012658811,0.00033318822,0.00027224806,0.0...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.903002917766571,-0.834099292755127,-0.8482...",[],"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...","[(100, 159)]","[(100, 157)]","[(125, 135)]",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91704,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.6,0.8,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 65)]","[(1, 53)]"
91705,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.0,0.0,0.0,0.0,0.2,0.4,0.4,0.4,0.4,0.4,0.4,0...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(19, 143)]","[(33, 80)]"
91706,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.4,0.4,0.4,0.4,0.6,0.6,0.6,0.6,0.6,0.8,0.8,0...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 91), (235, 324)]","[(9, 84)]"
91707,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.6,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1...","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 106)]","[(1, 44)]"
91708,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.6,0.8,0.8,0.8,0.8,0.8,0.8,1.0,1.0,1.0,1.0,1...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 65)]","[(1, 54)]"

In [49]:
len(set(seqs_to_keep).difference(filtered_seqs_no_paddle['name']))

3925

In [50]:
len(set(filtered_seqs_no_paddle['name']).difference(seqs_to_keep))

0

In [51]:
filtered_seqs_no_paddle.to_csv('../predictions/combined_preds/y1000_filtered_no_paddle_combined.csv')