In [2]:
import pandas as pd
import ast

In [3]:
# These are representative cluster sequences for the full length TFs
# in the test set of Sanborn that we use to test

seqs_to_remove = ['g000011.m1_saccharomyces_paradoxus.final',
'g001558.m1_saccharomyces_arboricola.final',
'g005241.m1_saccharomyces_mikatae.final',
'g003121.m1_saccharomyces_eubayanus.final',
'g005100.m1_saccharomyces_paradoxus.final',
'g000689.m1_saccharomyces_cerevisiae.final',
'g001197.m1_saccharomyces_arboricola.final',
'g000300.m1_saccharomyces_uvarum.final',
'g000966.m1_saccharomyces_eubayanus.final',
'g002878.m1_saccharomyces_kudriavzevii.final',
'g002484.m1_saccharomyces_mikatae.final',
'g002667.m1_saccharomyces_cerevisiae.final',
'g004608.m1_saccharomyces_paradoxus.final',
'g001455.m1_saccharomyces_kudriavzevii.final',
'g003829.m1_saccharomyces_kudriavzevii.final',
'P07249',
'g002480.m1_saccharomyces_uvarum.final']

In [3]:
def make_parrot_input(prefix): 

    # Non-y1000 seqs
    all_combined_no_y1000 = pd.read_csv(f'../predictions/combined_preds/non_cl_seqs_{prefix}_combined_filtered.csv', 
                                  index_col=0,
                                  converters={'combined_preds' : ast.literal_eval})

    # y1000 seqs
    all_combined_y1000 = pd.read_csv(f'../predictions/combined_preds/y1000_filtered_{prefix}_combined.csv', 
                                  index_col=0,
                                  converters={'combined_preds' : ast.literal_eval})

    all_combined_y1000 = all_combined_y1000[[n not in seqs_to_remove for n in all_combined_y1000['name']]]
    # Concatenate both!
    all_combined = pd.concat([all_combined_no_y1000, all_combined_y1000])

    # Make the predictions into parrot format
    all_combined = all_combined.reset_index(drop=True)
    preds_df = all_combined['combined_preds'].apply(pd.Series)

    # Join the new columns back to the original DataFrame (drop old combined_preds)
    parrot_input = pd.concat([all_combined[['name', 'sequence']], preds_df], axis=1)

    parrot_input.to_csv(f'../predictions/combined_preds/final_data/parrot_input_{prefix}.tsv', sep='\t', index=False, header=False)
    
    return all_combined

# Creating parrot input

In [4]:
no_comp_combined = make_parrot_input('no_composition')
no_comp_combined

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals
0,Aco021664.1,MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[23948.734,34398.383,34643.266,30163.777,46331...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.20640308,0.2299711,0.23149782,0.22729242,0....","[0.000457561,0.0005376012,0.00062079023,0.0016...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.15613313,0.1687365,0.17277826,0.17923725,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7733858227729797,-0.8443028330802917,-0.80...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
1,Aco014880.1,MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[163864.33,166590.23,153676.1,149345.64,139923...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.617012,0.60880744,0.6142499,0.6240743,0.621...","[0.08309816,0.17942944,0.29228172,0.2683431,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[7.2677155,7.249478,7.1840224,7.1038427,7.0258...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.41324320435523987,0.2205643206834793,0.3367...",[],"[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.8, 0.8, ...","[(0, 51)]","[(0, 53)]","[(7, 24)]","[(0, 66)]",NaN
2,Aco002151.1,MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[40901.55,39849.902,44446.395,46577.89,48848.3...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15860836,0.16032039,0.16562296,0.16951677,0...","[0.0013301629,0.001206241,0.0013138953,0.00109...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.052201796,-0.056321103,-0.05690101,-0.0570...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.5648762583732605,-0.554851233959198,-0.579...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
3,Aco018224.1,MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[52955.406,57674.707,60400.03,63605.56,59457.2...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.189424,0.18299682,0.17208093,0.16736288,0.1...","[0.0027180198,0.0023544286,0.0015037733,0.0013...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.034381293,-0.034525078,-0.033828054,-0.032...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.8527296781539917,-0.8746128082275391,-0.93...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(395, 436)]","[(207, 260), (381, 448)]",NaN,"[(194, 261), (369, 449)]",NaN
4,Aco005374.1,MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[21428.078,23407.145,33649.83,28168.95,34537.4...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.19193147,0.19046147,0.17961264,0.1756722,0....","[0.0016205282,0.0021502455,0.004893229,0.00514...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.31436068,0.3567606,0.38733268,0.38166854,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.958437442779541,-1.0686415433883667,-1.035...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230279,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 1.0, ...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(0, 65)]"
230280,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.2, 0.2, 0.2, 0.2, 0.4, 0.6, 0.6, 0.6, 0.6, ...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(0, 164)]","[(19, 143)]"
230281,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.6, 0.6, 0.6, 0.6, 0.8, 0.8, 0.8, 0.8, 0.8, ...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]"
230282,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 138)]","[(0, 106)]"
230283,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 1.0, 1.0, ...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 92)]","[(0, 65)]"

In [5]:
all_six_combined = make_parrot_input('all_six')
all_six_combined

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,adhunter_ensemble_centers,adhunter_ensemble_preds,adhunter_ensemble_uncertainty,combined_preds,adhunter_intervals,tada_intervals,adpred_intervals,paddle_intervals,adhunter_ensemble_intervals,composition_intervals,length
0,Aco021664.1,MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[23948.734,34398.383,34643.266,30163.777,46331...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.20640308,0.2299711,0.23149782,0.22729242,0....","[0.000457561,0.0005376012,0.00062079023,0.0016...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.15613313,0.1687365,0.17277826,0.17923725,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.7733858227729797,-0.8443028330802917,-0.80...",[],"[0.0, 0.0, 0.0, 0.16666666666666666, 0.1666666...",NaN,NaN,NaN,NaN,NaN,"[(3, 47)]",NaN
1,Aco014880.1,MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[163864.33,166590.23,153676.1,149345.64,139923...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.617012,0.60880744,0.6142499,0.6240743,0.621...","[0.08309816,0.17942944,0.29228172,0.2683431,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[7.2677155,7.249478,7.1840224,7.1038427,7.0258...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.41324320435523987,0.2205643206834793,0.3367...",[],"[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.66666666...","[(0, 51)]","[(0, 53)]","[(7, 24)]","[(0, 66)]",NaN,NaN,NaN
2,Aco002151.1,MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[40901.55,39849.902,44446.395,46577.89,48848.3...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.15860836,0.16032039,0.16562296,0.16951677,0...","[0.0013301629,0.001206241,0.0013138953,0.00109...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.052201796,-0.056321103,-0.05690101,-0.0570...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.5648762583732605,-0.554851233959198,-0.579...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aco018224.1,MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[52955.406,57674.707,60400.03,63605.56,59457.2...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.189424,0.18299682,0.17208093,0.16736288,0.1...","[0.0027180198,0.0023544286,0.0015037733,0.0013...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[-0.034381293,-0.034525078,-0.033828054,-0.032...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.8527296781539917,-0.8746128082275391,-0.93...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[(395, 436)]","[(207, 260), (381, 448)]",NaN,"[(194, 261), (369, 449)]",NaN,NaN,NaN
4,Aco005374.1,MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[21428.078,23407.145,33649.83,28168.95,34537.4...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.19193147,0.19046147,0.17961264,0.1756722,0....","[0.0016205282,0.0021502455,0.004893229,0.00514...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[0.31436068,0.3567606,0.38733268,0.38166854,0....","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.958437442779541,-1.0686415433883667,-1.035...",[],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230279,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[225855.17,207959.2,214425.17,223307.27,225141...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65906304,0.63379836,0.6176206,0.6227988,0.6...","[0.19796963,0.22446834,0.33828056,0.2870873,0....","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[9.423365,9.406331,9.351312,9.410977,9.433591,...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.2860097885131836,1.0973302125930786,1.05834...",[],"[0.6666666666666666, 0.8333333333333334, 0.833...","[(0, 61)]","[(0, 72), (98, 167)]","[(8, 37), (124, 135)]","[(0, 83), (85, 177)]","[(0, 65)]","[(1, 53)]",311.0
230280,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[26285.61,44107.375,35755.492,57085.26,44130.0...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.18617076,0.21403518,0.2531178,0.35214344,0....","[3.907744e-05,2.8722121e-05,2.6607286e-05,2.07...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[5.6288176,5.7803884,5.9316216,6.093204,6.3067...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[-0.3163558542728424,-0.20380930602550507,0.02...",[],"[0.16666666666666666, 0.16666666666666666, 0.1...","[(5, 86), (87, 140)]","[(4, 147)]","[(38, 56), (112, 122)]","[(0, 164)]","[(19, 143)]","[(33, 80)]",259.0
230281,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[83787.2,45584.32,62179.4,86906.56,110683.0,96...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.55249566,0.541711,0.56877726,0.6007034,0.63...","[0.023458298,0.019233154,0.021050513,0.0213846...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.679601,10.761075,10.826874,10.855729,10.85...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.9690939784049988,0.9031744003295898,0.57360...",[],"[0.5, 0.5, 0.5, 0.5, 0.6666666666666666, 0.666...","[(4, 87), (111, 190)]","[(0, 193), (225, 277)]","[(29, 55), (57, 66), (155, 170)]","[(0, 182), (235, 295)]","[(0, 91), (235, 324)]","[(9, 84)]",374.0
230282,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[260120.9,259477.33,261930.88,267912.47,254800...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.65554273,0.6494029,0.6350417,0.6165907,0.62...","[0.57603806,0.843381,0.9581022,0.99537665,0.99...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.004183,9.951009,9.830048,9.733973,9.650413...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[0.6035462021827698,0.5497061014175415,0.74318...",[],"[0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[(0, 55), (64, 108)]","[(0, 57), (59, 126), (259, 307)]","[(1, 27)]","[(0, 138)]","[(0, 106)]","[(1, 44)]",358.0
230283,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[227375.88,213626.03,196597.81,177447.86,18220...","[20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,...","[0.62806886,0.6239215,0.63666135,0.66077507,0....","[0.27208185,0.44481897,0.554567,0.5449341,0.52...","[27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,...","[10.570608,10.56903,10.524734,10.490515,10.458...","[27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,...","[1.0420730113983154,0.8350744247436523,0.92353...",[],"[0.6666666666666666, 0.8333333333333334, 0.833...","[(0, 53), (90, 130)]","[(0, 75), (86, 153)]","[(7, 38)]","[(0, 92)]","[(0, 65)]","[(1, 54)]",268.0

In [6]:
no_adhunter_ensemble_combined = make_parrot_input('no_ADhunterEnsemble')

In [7]:
no_adhunter_lite_combined = make_parrot_input('no_ADhunterLite')

In [4]:
no_tada_combined = make_parrot_input('no_tada')

In [5]:
no_paddle_combined = make_parrot_input('no_paddle')

In [6]:
no_adpred_combined = make_parrot_input('no_adpred')

# Making sure input has the right sequences

In [ ]:
with open('../all_seq_names.txt', 'r') as f:
    all_seqs = f.readlines()

all_seqs = [s.strip() for s in all_seqs]
all_seqs_set = set(all_seqs)

In [ ]:
print(all_seqs_set.difference(no_comp_combined['name']))
print(set(no_comp_combined['name']).difference(all_seqs_set))

print(all_seqs_set.difference(all_six_combined['name']))
print(set(all_six_combined['name']).difference(all_seqs_set))

print(all_seqs_set.difference(no_adhunter_ensemble_combined['name']))
print(set(no_adhunter_ensemble_combined['name']).difference(all_seqs_set))

print(all_seqs_set.difference(no_adhunter_lite_combined['name']))
print(set(no_adhunter_lite_combined['name']).difference(all_seqs_set))

print(all_seqs_set.difference(no_paddle_combined['name']))
print(set(no_paddle_combined['name']).difference(all_seqs_set))

print(all_seqs_set.difference(no_tada_combined['name']))
print(set(no_tada_combined['name']).difference(all_seqs_set))

print(all_seqs_set.difference(no_adpred_combined['name']))
print(set(no_adpred_combined['name']).difference(all_seqs_set))

# Make regression input

In [5]:
all_combined_regression = pd.read_csv(f'../regression_input/all_data_combined_normalized_preds.csv', 
                                  index_col=0,
                                  converters={'combined_normalized_preds' : ast.literal_eval})
all_combined_regression

,name,sequence,combined_normalized_preds
0,Aco021664.1,MELERQDKEEEEEEEEELLRTAAAVPMHRFIVPKPEPMELFGSLQL...,"[0.11518569115989387, 0.11519906111884536, 0.1..."
1,Aco014880.1,MGSPENPNWYLDCALIDELPVADGGLCWSAQGFNSSSNVSLETDGP...,"[0.4737106008651146, 0.489801830763867, 0.5086..."
2,Aco002151.1,MLLHPRSAFSTYARVGSHDIGSLAAGRHVGSAAAVNVHRRLFGFIR...,"[0.11020145549684952, 0.11018075551463824, 0.1..."
3,Aco018224.1,MFVFENQSRDSSSPVSKQSNGRGFPSHLLLLLRLAAAAAAAAAAAA...,"[0.12885461613803906, 0.12879388166437314, 0.1..."
4,Aco005374.1,MEFRSNQDDDMGLPSSLSYNNNNNNNNNNNNNNSSNNPLPIRGSAF...,"[0.0989018179411567, 0.09899030220977273, 0.09..."
...,...,...,...
230124,g003885.m1_yHMPu5000037205_zygotorulaspora_dan...,MNALHGTDVFDLFDLENGDDIDFETAYKMISTFDDEMVLPKMNFVE...,"[0.6222801366030123, 0.793373162336333, 0.8123..."
230125,g001397.m1_yHMPu5000037210_Kazachstania_jingho...,MSNQNNDHNHHPNHNHQPRHHPHQDSHHTTDRSHMEMHDIFDLDTE...,"[0.147797102123685, 0.14779537236551396, 0.147..."
230126,g003574.m1_yHMPu5000037837_Vanderwaltozyma_ver...,MDTTNSLFDSINTITTTNLSTSSTTTDNVKDFNNLFDDDFDLGIDF...,"[0.5255622280303153, 0.5248564576568775, 0.525..."
230127,g004154.m1_yHQL494_Lachancea_sp_nov_plate34_PL...,MENEHLLDVFDYDLDIDFETAYEMINNEDQVFKGNNENHMAIDPEV...,"[0.6549185317875111, 0.8662423099277136, 0.885..."
230128,g004418.m1_zygosaccharomyces_bailii.final,MDAVGTGDMFDLFDLDNENDIDFETAYKMISNFDDATSSLNDDILP...,"[0.7356990582187916, 0.9312198282459493, 0.949..."

In [6]:
all_combined_regression = all_combined_regression[[n not in seqs_to_remove for n in all_combined_regression['name']]]

In [8]:
all_combined_regression = all_combined_regression.reset_index(drop=True)
preds_df = all_combined_regression['combined_normalized_preds'].apply(pd.Series)

# Join the new columns back to the original DataFrame (drop old combined_preds)
parrot_input = pd.concat([all_combined_regression[['name', 'sequence']], preds_df], axis=1)

parrot_input.to_csv(f'../regression_input/parrot_input_regression_normalized.tsv', sep='\t', index=False, header=False)